name: 'Setup'
description: 'Node setup, install, and build'
inputs:
  node_version:
    description: 'Node.js version to setup'
    required: false
    default: '18.x'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
    - name: Install npm packages
      run: |
        npm install
      shell: bash
    - name: Build typescript
      run: npm run build
      shell: bash
