name: End to end testing

on:
  workflow_dispatch: {}

jobs:
  e2e-tests:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        uses: ./.github/actions/e2e-testing/edge/action.yml
